### ISSUE TITLE
Search results link to Hackage, not Stackage.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stackage-server#194]
https://www.stackage.org/lts-6.11/hoogle?q=amazonka

**Comment by chrisdone** [comment]
Good catch. Expanding: https://www.stackage.org/lts-6.11/hoogle?q=base

It's the `package` results that link to Hackage. The output from Hoogle needs a bit more munging.

**Comment by chreekat** [comment]
Looks fixed.
