### ISSUE TITLE
Is it possible to have local instance?

### ISSUE THREAD

**Issue by sigrlami** [commercialhaskell/stackage-server#233]
I want to have local instance of stackage, where 
1. I can have specific LTS downloaded on local server 
2. Custom package set on local server 

Is it possible with current structure? How do I point `stack` to local instance?

I know I can run `stackage-server` as is. Is there a guide how to setup local snapshots?

**Comment by snoyberg** [comment]
This isn't an intended use case, and the server code isn't designed for
this. Extensible snapshots in the next Stack release will provide a much
easier way to provide custom snapshots.
