### ISSUE TITLE
Package display discrepancy regarding dependencies and READMEs

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stackage-server#276]
@cutculus originally reported the following on commercialhaskell/stackage#3240

Not sure if this is a Stackage issue or a package maintainer issue, so please bear with me.

`tasty-0.11.3` (LTS 10.4) has a dependency on `regex-tdfa` which was [recently removed](https://github.com/feuerbach/tasty/commit/3ea4cce03149dfc419601065da1baabf83637677#diff-04c6e90faac2675aa89e2176d2eec7d8R295) for version `1.0` ([Hackage](https://hackage.haskell.org/package/tasty-1.0)). However, the [page](https://www.stackage.org/lts-10.4/package/tasty-0.11.3) for the package on LTS 10.4 shows an updated README, instead of the old one. This can be confusing because (1) `0.11.3` does actually depend on `regex-tdfa`, contrary to what the new README implies and (2) the default page on Stackage, doesn't show dependencies for version `0.11.3` correctly - right now, it reads

> Depends on 12 packages:
> ansi-terminal, async, base, clock, containers, deepseq, mtl, optparse-applicative, stm, tagged, unbounded-delays, unix

whereas Hackage is correct

> ansi-terminal (>=0.6.2), async (>=2.0), base (>=4.5 && <5), clock (>=0.4.4.0), containers, deepseq (>=1.3), ghc-prim, mtl, optparse-applicative (>=0.11), regex-tdfa (>=1.1.8.2), stm (>=2.3), tagged (>=0.5), unbounded-delays (>=0.1), unix

**Comment by chreekat** [comment]
I suspect this issue can be closed.

The changelog on https://www.stackage.org/lts-10.4/package/tasty-0.11.3 looks correct.

I don't understand  "0.11.3 does actually depend on regex-tdfa, contrary to what the new README implies". The README doesn't imply any dependencies.

Please reopen with clarifications if necessary!
