### ISSUE TITLE
Allow customizing badge color

### ISSUE THREAD

**Issue by pgujjula** [commercialhaskell/stackage-server#329]
Currently, Stackage badges show up as green. But it's common for badges representing published versions of software to be blue (some examples: [ex 1](https://github.com/twpayne/chezmoi), [ex 2](https://github.com/senchalabs/connect), [ex 3](https://github.com/kimwalisch/primesieve)). It would be useful to be able to customize the badge color with a query string. [shields.io](https://shields.io/badges/hackage-version) does this for Hackage.

**Comment by chreekat** [comment]
Hey @pgujjula, can you point me to an example of a current Stackage badge?

**Comment by pgujjula** [comment]
I'm using the current Stackage badge in my project here: https://github.com/pgujjula/apply-merge

**Comment by pgujjula** [comment]
Sure, here's some examples: [Shelly](https://github.com/gregwebs/Shelly.hs), [bitvec](https://github.com/Bodigrim/bitvec), [world-peace](https://github.com/cdepillabout/world-peace)

**Comment by pgujjula** [comment]
Sounds good, thanks!

**Comment by pgujjula** [comment]
Sounds good, thanks for the consideration!

**Comment by chreekat** [comment]
Would you want to contribute a patch? I myself won't have time for this right now. :)

**Comment by pgujjula** [comment]
Yeah I can work on it sometime this week :)

**Comment by pgujjula** [comment]
Hey @chreekat, I went through the README to set up the project. I was able to successfully run the dev server with `yesod devel`, but it seems like there's no packages, so I can't test badges. In order to run the postgresql-based server, I tried running the cron job to set up the database, but I get an error:
```shellsession
$ export PGSTRING=postgresql://postgres:postgres@localhost:5432/stackage
$ stack exec stackage-server-cron
*** Exception: CredentialChainExhausted
```
`CredentialChainExhausted` is an amazonka error, do I need access to AWS?

**Comment by pgujjula** [comment]
Or perhaps there is a simpler way for me to get test data for development?

**Comment by chreekat** [comment]
Oof, I forgot about that. I don't know how to get around the problem of missing packages. (I'm still new to maintaining this project, so maybe there's a way I just don't know.)

I think creating test data for local development is worth its own issue. But it doesn't have to block the badge color project.

For badge color, go ahead and put up a PR when you think it seems good enough. We can fall back and rely on code review and testing it live :upside_down_face:

**Comment by pgujjula** [comment]
I opened a PR here: https://github.com/commercialhaskell/stackage-server/pull/331 :)
