### ISSUE TITLE
I been blocked by Cloudflare when haddock page

### ISSUE THREAD

**Issue by ncaq** [commercialhaskell/stackage-server#337]
![image](https://github.com/user-attachments/assets/a5eb55be-037e-4218-8f3a-ac89b8ace098)

I search symbol by name and open link.
The link is `https://www.stackage.org/haddock/nightly-2024-11-04/megaparsec-9.6.1/Text-Megaparsec.html`
I been blocked haddock page.
And otherwise haddock page too.
`Cloudflare Ray ID: 8dd8c216487e32d9`

**Comment by chreekat** [comment]
Thanks for opening an issue! I can reproduce the problem. I'll look into it.

**Comment by chreekat** [comment]
I suspect this is related:
https://discourse.haskell.org/t/hoogle-appears-to-be-down/10408/23

**Comment by chreekat** [comment]
I may have fixed it now. Let me know if you still have issues!

https://discourse.haskell.org/t/stackage-outage-2024-11-04/10680

**Comment by chreekat** [comment]
20 minutes later, the analytics look good. Closing for now.

**Comment by ncaq** [comment]
Thank you!
